#+Title: Professional Statement Outline
#+Author: Alex Schexnayder

* 3 Strengths
- Strong written and verbal skills
- programmatic thinking
- coding abilities

* 2 Values
- protecting people
- making organizations better at protecting their people

* Clarifying Questions
- what most interests me?
  - penetration testing
  - incident response
- who is the audience for my professional statement
  - private sector recruiters/employers
- In what ways can my strengths, values, and interest in cybersecurity support the security goals of various organizations?

  
* How to refine the statement
Pro Tip: Save a copy of your work
Finally, be sure to save a copy of your completed activity. You can use it for your professional portfolio to demonstrate your knowledge and/or experience to potential employers.

What to Include in Your Response

Be sure to address the following elements in your completed activity:

Be intentional about how you want to be perceived by potential employers. 

Include your strengths and values, and be genuine about why you want to enter the cybersecurity profession.

Regularly update your statement to reflect your growing professional skills and knowledge. 
